"""Assemble the three agent outputs into one shareable markdown report."""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime, timezone

from . import config
from .agents import SECTION_BD, SECTION_MARKET, SECTION_TECH

SECTION_HEADINGS = [SECTION_MARKET, SECTION_TECH, SECTION_BD]

_DISCLAIMER = (
    "Generated by an AI crew using live web search. Numbers carry the source they came from; "
    "anything marked *(unverified estimate)* could not be confirmed. Verify critical figures "
    "before committing money."
)


@dataclass
class RunMeta:
    product: str
    model_research: str
    model_writer: str
    searches_used: int = 0
    search_budget: int = 0
    duration_seconds: float = 0.0
    started_at: datetime | None = None

    def timestamp_line(self) -> str:
        if self.started_at is None:
            generated = "just now"
        else:
            generated = self.started_at.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
        duration = f" · {self.duration_seconds:.0f}s" if self.duration_seconds else ""
        searches = f" · {self.searches_used} web searches" if self.searches_used else ""
        return f"*Generated {generated}{duration}{searches}*"

    def method_line(self) -> str:
        budget = self.search_budget * 3
        return (
            f"**Method** — CrewAI sequential crew, 3 agents. Research: `{self.model_research}`, "
            f"business development: `{self.model_writer}`. Search budget: {budget} Serper queries "
            "per run (one-time free tier)."
        )


@dataclass
class AnalysisResult:
    product: str
    report_markdown: str
    raw_sections: dict[str, str] = field(default_factory=dict)
    meta: RunMeta | None = None

    @property
    def total_words(self) -> int:
        return len(self.report_markdown.split())


def slugify(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", ascii_value).strip("-").lower()
    return slug[:60] or "report"


def report_filename(product: str, extension: str = "md") -> str:
    return f"bizdev-report-{slugify(product)}.{extension}"


def _norm_heading(line: str) -> str | None:
    """Normalize a markdown heading line to a comparable title, or None if not a heading."""
    match = re.match(r"^#{1,6}\s*(.+?)\s*:?\s*$", line.strip())
    if not match:
        return None
    return re.sub(r"^\d+\s*[.)]\s*", "", match.group(1)).strip().lower()


def normalize_section(raw: str, heading: str) -> str:
    """Make an agent's output start cleanly at its canonical heading.

    Agents occasionally prepend a top-level title, wrap output in a code fence, or
    renumber the heading. This guarantees the canonical heading appears exactly once,
    first, followed by a blank line so markdown renders correctly.
    """
    text = (raw or "").strip()
    if not text:
        return f"{heading}\n\n_This section returned no content._"

    text = re.sub(r"^#\s+[^\n]*\n+", "", text, count=1)
    text = re.sub(r"^(?:```markdown|```md)\s*\n+", "", text)
    text = re.sub(r"\n+```\s*$", "", text)

    lines = text.splitlines()
    target = _norm_heading(heading)

    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and _norm_heading(lines[0]) == target:
        lines.pop(0)
        while lines and not lines[0].strip():
            lines.pop(0)

    body = "\n".join(lines).strip()
    if not body:
        return f"{heading}\n\n_This section returned no content._"
    return f"{heading}\n\n{body}"


def assemble_report(product: str, sections: dict[str, str], meta: RunMeta) -> str:
    """Concatenate the fixed sections into one document. No synthesis LLM call."""
    keys = ["market", "tech", "bd"]
    headings = {
        "market": SECTION_MARKET,
        "tech": SECTION_TECH,
        "bd": SECTION_BD,
    }

    body_parts: list[str] = []
    for key in keys:
        body_parts.append(normalize_section(sections.get(key, ""), headings[key]))

    header = (
        f"# Business Development Report: {product}\n\n"
        f"{meta.timestamp_line()}\n\n"
        f"{meta.method_line()}\n\n"
        f"> {_DISCLAIMER}\n\n"
        "---\n\n\n"
    )
    return header + "\n\n".join(body_parts) + "\n"


def configuration_summary() -> list[tuple[str, str]]:
    """(label, value) pairs for the UI sidebar. Never includes key values."""
    return [
        ("Research model", config.RESEARCH_MODEL),
        ("Writer model", config.WRITER_MODEL),
        ("Searches per agent", str(config.DEFAULT_MAX_SEARCHES_PER_AGENT)),
        ("Results per search", str(config.DEFAULT_MAX_RESULTS)),
    ]
